trigger:
  branches:
    include:
    - master
    - dev
variables:
- name: buildConfiguration
  value: 'Release'
- name: solutionFile
  value: 'EStore.sln'
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UseDotNet@2
      inputs:
        version: '5.0.x'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '$(solutionFile)'
        arguments: '--configuration $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration) --filter Build=CI --collect:"XPlat Code Coverage" /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(build.artifactstagingdirectory)/TestResults/coverage.cobertura.xml'